/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cell/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live */
        get: operations["get_live_api_cell_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cell/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Timeline
         * @description State history of the current shift, from its start to now — for the live andon bar.
         *
         *     Polled by the front (it is not pushed over the WebSocket: a shift's timeline changes only
         *     a few times a minute, not worth a place in the 4 Hz live payload).
         */
        get: operations["get_timeline_api_cell_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Oee */
        get: operations["get_oee_api_oee_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stops
         * @description Stops qualifiable by an operator: not planned, at least ``oee.micro_stop_s`` long
         *     (the open stop included, as soon as it reaches that duration).
         */
        get: operations["list_stops_api_stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Qualify */
        patch: operations["qualify_api_stops__stop_id__patch"];
        trace?: never;
    };
    "/api/stops/pareto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pareto */
        get: operations["pareto_api_stops_pareto_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weld": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weld */
        get: operations["get_weld_api_weld_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveOut */
        LiveOut: {
            /** Now */
            now: string | null;
            /** State */
            state: number | null;
            /** Fault Code */
            fault_code: number | null;
            /** Stop Origin */
            stop_origin: number | null;
            /** Comm Lost */
            comm_lost: boolean;
            /** Comm Lost Since */
            comm_lost_since: string | null;
            /** Good Total */
            good_total: number | null;
            /** Scrap Total */
            scrap_total: number | null;
            /** Theoretical Cycle S */
            theoretical_cycle_s: number | null;
            /** Last Cycle S */
            last_cycle_s: number | null;
            /** Weld Current Ka */
            weld_current_ka: number | null;
            /** Weld Points Since Cap Change */
            weld_points_since_cap_change: number | null;
            open_stop: components["schemas"]["StopOut"] | null;
            /** Stops Rev */
            stops_rev: number;
            oee: components["schemas"]["OeeOut"] | null;
        };
        /** OeeOut */
        OeeOut: {
            /** Label */
            label: string;
            /** Window Start */
            window_start: string;
            /** Window End */
            window_end: string;
            /** Gap S */
            gap_s: number;
            /** Opening S */
            opening_s: number;
            /** Planned Stop S */
            planned_stop_s: number;
            /** Planned S */
            planned_s: number;
            /** Fault S */
            fault_s: number;
            /** Setup S */
            setup_s: number;
            /** Starved S */
            starved_s: number;
            /** Blocked S */
            blocked_s: number;
            /** Manual S */
            manual_s: number;
            /** Micro S */
            micro_s: number;
            /** Operating S */
            operating_s: number;
            /** Good */
            good: number;
            /** Scrap */
            scrap: number;
            /** Dropped Parts */
            dropped_parts: number;
            /** Availability */
            availability: number | null;
            /** Performance */
            performance: number | null;
            /** Quality */
            quality: number | null;
            /** Oee */
            oee: number | null;
            /** Anomalies */
            anomalies: string[];
        };
        /** ParetoBucketOut */
        ParetoBucketOut: {
            /** Key */
            key: string;
            /** Duration S */
            duration_s: number;
            /** Count */
            count: number;
            /** Unqualified Duration S */
            unqualified_duration_s: number;
            /** Unqualified Count */
            unqualified_count: number;
        };
        /** ParetoOut */
        ParetoOut: {
            /** By */
            by: string;
            /** Metric */
            metric: string;
            /** Buckets */
            buckets: components["schemas"]["ParetoBucketOut"][];
            /** Micro Count */
            micro_count: number;
            /** Micro Duration S */
            micro_duration_s: number;
        };
        /** QualifyIn */
        QualifyIn: {
            /** Cause */
            cause: string;
        };
        /** StopOut */
        StopOut: {
            /** Id */
            id: number;
            /** Start Ts */
            start_ts: string;
            /** End Ts */
            end_ts: string | null;
            /** Duration S */
            duration_s: number;
            /** Open */
            open: boolean;
            /** State */
            state: number;
            /** Origin Station */
            origin_station: string;
            /** Fault Code */
            fault_code: number;
            /** Suggested Category */
            suggested_category: string | null;
            /** Qualified Cause */
            qualified_cause: string | null;
            /** Qualified At */
            qualified_at: string | null;
        };
        /** TimelineOut */
        TimelineOut: {
            /** Window Start */
            window_start: string | null;
            /** Now */
            now: string | null;
            /** Segments */
            segments: components["schemas"]["TimelineSegmentOut"][];
        };
        /** TimelineSegmentOut */
        TimelineSegmentOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** State */
            state: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeldBucketOut */
        WeldBucketOut: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Avg Ka */
            avg_ka: number | null;
            /** Min Ka */
            min_ka: number | null;
            /** Max Ka */
            max_ka: number | null;
            /** Points */
            points: number;
            /** Points Nok */
            points_nok: number;
            /** Scrap Rate */
            scrap_rate: number | null;
        };
        /** WeldMarkerOut */
        WeldMarkerOut: {
            /** Ts */
            ts: string;
            /** Kind */
            kind: string;
        };
        /** WeldOut */
        WeldOut: {
            /** Bucket S */
            bucket_s: number;
            /** Nominal Ka */
            nominal_ka: number;
            /** Tolerance Pct */
            tolerance_pct: number;
            /** Buckets */
            buckets: components["schemas"]["WeldBucketOut"][];
            /** Markers */
            markers: components["schemas"]["WeldMarkerOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_live_api_cell_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
        };
    };
    get_timeline_api_cell_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
        };
    };
    get_oee_api_oee_get: {
        parameters: {
            query: {
                group_by?: ("shift" | "day") | null;
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OeeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stops_api_stops_get: {
        parameters: {
            query?: {
                unqualified?: boolean;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qualify_api_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pareto_api_stops_pareto_get: {
        parameters: {
            query: {
                by?: "cause" | "station" | "fault_code";
                metric?: "duration" | "count";
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParetoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weld_api_weld_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
